name: Docker Build, Run and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set image name 
        id: image
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Docker Metadata (commit ID + latest)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.image.outputs.IMAGE_NAME }}
          tags: |
            type=sha,format=short,prefix=
            type=raw,value=latest

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Container to Verify 
        run: |
          IMAGE="${{ steps.image.outputs.IMAGE_NAME }}:latest"
          docker pull "$IMAGE"
          docker run -d -p 8080:8080 --name test-container "$IMAGE"
          sleep 10
          docker logs test-container
          docker stop test-container
          docker rm test-container
