name: Build and push Docker Image to GHCR

on:
  push:
     branches:
       - main
  workflow_dispatch:

jobs:
  build-run-push:
     runs-on: ubuntu-latest

     permissions:
             contents: read
             packages: write

     steps:
       - name: Checkout sourcecode
         uses: actions/checkout@v4

       - name: Login to GHCR
         uses: docker/login-action@v3
         with: 
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

       - name: Set up Docker metadata
         id: meta
         uses: docker/metadata-actions@v5
         with:
            images: ghcr.io/${{ github.repository }}
            tags:  |
               type=ref,event=branch
               type=sha
               type=semver,pattern={{version}}
            flavor: ""

       - name: Build and push Docker Image
         uses: docker/build-push-action@v5
         with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tag }}
            labels: ${{ steps.meta.outputs.labels }}

       - name: run container to verify
         run:  |
            IMAGE=$(echo ${{ steps.meta.outputs.tag }} | cut -d',' -f1)
            docker run -d -p 8080:8080 --name test-container $IMAGE
            sleep 10
            docker logs test-container
            docker stop test-container
            docker rm test-container
            
  
