name: Build and push Docker Image to GHCR

on:
  push:
     branches:
       - main
  workflow_dispatch:

jobs:
  build-run-push:
     runs-on: ubuntu-latest

     permissions:
             contents: read
             packages: write

     steps:
       - name: Checkout sourcecode
         uses: actions/checkout@v4

       - name: Login to GHCR
         uses: docker/login-action@v3
         with: 
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

       - name: Build Docker Image
         run: |
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            IMAGE_TIMESTAMP=ghcr.io/payaldevi02/work-spp:$TIMESTAMP
            IMAGE_LATEST=ghcr.io/payaldevi02/workapp:latest
            echo "Building images: $IMAGE_TIMESTAMP and $IMAGE_LATEST"
            docker build -t $IMAGE_TIMESTAMP -t $IMAGE_LATEST .
        

       - name: Run Docker Container
         run: |
              docker run -d -p 8080:8080 --name test-container ghcr.io/payaldevi02/work-app:latest
              sleep 10
              docker logs test-container
              docker stop test-container
              docker rm test-container
              

       - name: Push Docker Image to GHCR
         run: docker push ghcr.io/payaldevi02/work-app:latest
              docker push ghcr.io/payaldevi02/work-app:$TIMESTAMP
