name: Build and push Docker Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-run-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout source code
      - name: Checkout sourcecode
        uses: actions/checkout@v4

      # Step 2: Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Generate tags using docker/metadata-action
      - name: Set Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=ref,event=branch
          flavor: |
            latest=true

      # Step 4: Build and push Docker image using those tags
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run container to verify image
        run: |
          echo "All tags: ${{ steps.meta.outputs.tags }}"
          IMAGE=$(echo "${{ steps.meta.outputs.tags }}" | cut -d',' -f1 | tr -d '[:space:]')
          echo "Running image: $IMAGE"
          docker run -d -p 8080:8080 --name test-container "$IMAGE"
          sleep 10
          docker logs test-container
          docker stop test-container
          docker rm test-container
