name: Build and push Docker Image to GHCR

on:
  push:
     branches:
       - main
  workflow_dispatch:

jobs:
  build-run-push:
     runs-on: ubuntu-latest

     permissions:
             contents: read
             packages: write

     steps:
       - name: Checkout sourcecode
         uses: actions/checkout@v4

       - name: Login to GHCR
         uses: docker/login-action@v3
         with: 
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

       - name: Generate Docker image metadata
         id: meta
         uses: docker/metadata-action@v5
         with:
            images: ghcr.io/${{ github.repository }}
            tags: |
              type=sha
              type=ref,event=branch
            flavor: |
              latest=true
        

       - name: Build-run-push Docker Image
         uses: docker/build-push-action@v5
         with:
           context: .
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}

       - name: Run container to verify
         run: |
            IFS=',' read -r FIRST_TAG _ <<< "${{ steps.meta.oututs.tags }}"
            IMAGE=$( echo "$FIRST_TAG" | tr -d '[:space:]')
            echo "Running image: $IMAGE"
            docker pull "$IMAGE"
            docker run -d -p 8080:8080 --name test-container "$IMAGE"
            sleep 10
            docker logs test-container
            docker stop test-container
            docker rm test-container
  
