name: Docker Build, Run and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
           distribution: temurin
           java-version: '17'

      - name: Build Maven Project
        run: mvn clean package -DskipTests  

      - name: Set image name 
        id: image
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Docker Metadata (commit ID + latest)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.image.outputs.IMAGE_NAME }}
          tags: |
            type=sha,format=short,prefix=
            type=raw,value=latest

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build  Docker Image
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}:latest"
           docker build -t $IMAGE_NAME .
           docker push $IMAGE_NAME
              .
      - name: Push Docker image
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}:latest"
           docker push $IMAGE_NAME
