name: Build and push Docker Image to GHCR

on:
  push:
     branches:
       - main
  workflow_dispatch:

jobs:
  build-run-push:
     runs-on: ubuntu-latest

     permissions:
             contents: read
             packages: write

     steps:
       - name: Checkout sourcecode
         uses: actions/checkout@v4

       - name: Login to GHCR
         uses: docker/login-action@v3
         with: 
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

       - name: Build-run-push Docker Image
         run: |
            REPO="ghcr.io/${{ github.repository }}"
            REPO_LOWER=$(echo "$REPO" | tr '[:upper:]' '[:lower:]')
            COMMIT_SHA=${GITHUB_SHA::7}

            IMAGE_SHA="$REPO_LOWER:$COMMIT_SHA"
            IMAGE_LATEST="$REPO_LOWER:latest"
            
            echo "Building images: $IMAGE_SHA and $IMAGE_LATEST"
            docker build -t $IMAGE_SHA -t $IMAGE_LATEST .
            
            docker run -d -p 8080:8080 --name test-container $IMAGE_LATEST
            sleep 10
            docker logs test-container
            docker stop test-container
            docker rm test-container
            
            docker push $IMAGE_LATEST
            docker push $IMAGE_SHA
