name: Docker Build, Run and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
     
      - name: Code Checkout
        uses: actions/checkout@v4

    
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/maven-demo
          tags: |
            type=sha,format=short,prefix=

     
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

     
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

 
      - name: Run container to verify
        run: |
          IMAGE="${{ steps.meta.outputs.tags }}"
          echo "Running image: $IMAGE"

          docker pull "$IMAGE"
          docker run -d -p 8080:8080 --name test-container "$IMAGE"
          sleep 10
          docker logs test-container
          docker stop test-container
          docker rm test-container
