name: Build and push Docker Image to GHCR

on:
  push:
     branches:
       - main
  workflow_dispatch:

jobs:
  build-run-push:
     runs-on: ubuntu-latest

     permissions:
             contents: read
             packages: write


     env:
        IMAGE_NAME: ghcr.io/payaldevi02/work-app

     steps:
       - name: Checkout sourcecode
         uses: actions/checkout@v4

       - name: Set image tag using branch and timestamp
         run: IMAGE_TAG="${GITHUB_REF##*/}-$(date +%Y%m%d-%H%M%S)"
              echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

       - name: Login to GHCR
         uses: docker/login-action@v3
         with: 
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

       - name: Build Docker Image
         run: docker build -t $IMAGE_NAME:${{ env.IMAGE_TAG }} .
              docker tag $IMAGE_NAME:${{ env.IMAGE_TAG }} $IMAGE_NAME

       - name: Run Docker Container
         run: docker run -d -p 8080:8080 --name test-container $IMAGE_NAME:$IMAGE_TAG
              sleep 10
              docker logs test-container

       - name: Push Docker Image to GHCR
         run: docker push $IMAGE_NAME:latest
